# Name:          load-ibceo-table.yml
# Purpose:       Download and extract NOAA IBCAO Arctic Bathymetry data.
# Author(s):     Nick Hughes
# Created:       2017-ix-4
# Modifications: 2017-ix-?  - 
# Copyright:     (c) Norwegian Meteorological Institute, 2017
# Citing:        https://doi.org/10.5281/zenodo.884048
#
# License:       This file is part of the BIFROST ice charting system.
#                BIFROST is free software: you can redistribute it and/or modify
#                it under the terms of the GNU General Public License as published by
#                the Free Software Foundation, version 3 of the License.
#                http://www.gnu.org/licenses/gpl-3.0.html
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
---

# http://www.ngdc.noaa.gov/mgg/bathymetry/arctic/grids/version3_0/IBCAO_V3_500m_RR_tif.zip [436 MB] Raw with multibeam
# http://www.ngdc.noaa.gov/mgg/bathymetry/arctic/grids/version3_0/IBCAO_V3_500m_SM_tif.zip [436 MB] Smoothed
# IBCAO SRID in PostGIS = 3996

- name: Creates tmp directory
  file: path=/tmp/ibcao state=directory

- name: download ibcao with multibeam file and unpack
  become: yes
  become_user: root
  unarchive: src=http://www.ngdc.noaa.gov/mgg/bathymetry/arctic/grids/version3_0/IBCAO_V3_500m_RR_tif.zip dest=/tmp/ibcao copy=no

- name: copy ibcao multibeam data to Ocean database
  shell: "export PGPASSWORD='bifrostadmin'; /usr/bin/raster2pgsql -s 3996 -I -C -M /tmp/ibcao/IBCAO_V3_500m_RR_tif/IBCAO_V3_500m_RR.tif -F -t 100x100 ibcao_500_rr | /usr/bin/psql -h localhost -p 5433 -d Ocean -U bifrostadmin"
  args:
    executable: /bin/bash

- name: download smoothed ibcao with topography file and unpack
  become: yes
  become_user: root
  unarchive: src=http://www.ngdc.noaa.gov/mgg/bathymetry/arctic/grids/version3_0/IBCAO_V3_500m_SM_tif.zip dest=/tmp/ibcao copy=no

- name: copy ibcao smoothed data to Ocean database
  shell: "export PGPASSWORD='bifrostadmin'; /usr/bin/raster2pgsql -s 3996 -I -C -M /tmp/ibcao/IBCAO_V3_500m_SM_tif/IBCAO_V3_500m_SM.tif -F -t 100x100 ibcao_500_sm | /usr/bin/psql -h localhost -d Ocean -U bifrostadmin"
  args:
    executable: /bin/bash
  
- name: delete tmp directory
  become: yes
  become_user: root
  file: path=/tmp/ibcao state=absent
