# Name:          install-gshhs-coastline.yml
# Purpose:       Download and extract NOAA GSHHG coastline data.
# Author(s):     Nick Hughes
# Created:       2017-ix-4
# Modifications: 2017-ix-?  - 
# Copyright:     (c) Norwegian Meteorological Institute, 2017
# Citing:        https://doi.org/10.5281/zenodo.884048
#
# License:       This file is part of the BIFROST ice charting system.
#                BIFROST is free software: you can redistribute it and/or modify
#                it under the terms of the GNU General Public License as published by
#                the Free Software Foundation, version 3 of the License.
#                http://www.gnu.org/licenses/gpl-3.0.html
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
---
- name: Creates tmp directory
  file: path=/tmp/gshhs_coastline state=directory

# See example at http://stackoverflow.com/questions/34087619/interpolate-a-variable-in-a-shell-command-run-by-ansible
- name: Check NOAA NGDC server for latest GSHHS coastline file name
  shell: URL=http://www.ngdc.noaa.gov/mgg/shorelines/data/gshhg/latest/; ZIPFN=`/usr/bin/wget -q -O - $URL | /bin/grep -o '<a .*href=.gshhg-shp.*>' | /bin/sed -e 's/<a /\n<a /g' | /bin/sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d'`; echo $URL$ZIPFN
  register: ZIPURL
  args:
    executable: /bin/bash

- name: download gshhs coastline file and unpack
  become: yes
  become_user: root
  unarchive: src={{ ZIPURL.stdout }} dest=/tmp/gshhs_coastline copy=no
  
- name: copy data to Ocean database
  shell: "export DETAIL={{ item }}; export PGPASSWORD='bifrostadmin'; /usr/bin/shp2pgsql -s 4326 -W LATIN1 \"/tmp/gshhs_coastline/GSHHS_shp/${DETAIL}/GSHHS_${DETAIL}_L1.shp\" \"gshhs_${DETAIL}\" | /usr/bin/psql -h localhost -p 5433 -d Ocean -U bifrostadmin"
  args:
    executable: /bin/bash
  with_items:
    - c
    - l
    - i
    - h
    - f
 
- name: delete tmp directory
  become: yes
  become_user: root
  file: path=/tmp/gshhs_coastline state=absent
