# Name:          load-scar-add-data.yml
# Purpose:       Download and extract SCAR Antarctic Digital Database coastline data.
# Author(s):     Nick Hughes
# Created:       2017-ix-4
# Modifications: 2017-ix-?  - 
# Copyright:     (c) Norwegian Meteorological Institute, 2017
# Citing:        https://doi.org/10.5281/zenodo.884048
#
# License:       This file is part of the BIFROST ice charting system.
#                BIFROST is free software: you can redistribute it and/or modify
#                it under the terms of the GNU General Public License as published by
#                the Free Software Foundation, version 3 of the License.
#                http://www.gnu.org/licenses/gpl-3.0.html
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
---
- name: Creates tmp directory
  file: path=/tmp/scar_add state=directory

# Sub-antarctic has gid, location (char 50), geom (multipolyon 4326)
# Main coastline has gid, surface (char 254), geom (multipolygon 4326)
- name: copy data to Ocean database
  include: roles/common/tasks/load-scar-add-table.yml zipname={{ item.zipname }} dbtable={{ item.dbtable }} mode={{ item.mode }} url={{ item.url }}
  with_items:
    - { zipname: 'Sub-antarctic_coastline_low_res_polygon',    dbtable: 'add_subant_coastline_l', mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Sub-antarctic_coastline_low_res_polygon.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2NvYXN0bGluZXMvc2hwL1N1Yi1hbnRhcmN0aWNfY29hc3RsaW5lX2xvd19yZXNfcG9seWdvbi56aXA%3D' }
    - { zipname: 'Coastline_low_res_polygon',                  dbtable: 'add_ant_coastline_l',    mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Coastline_low_res_polygon.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2NvYXN0bGluZXMvc2hwL0NvYXN0bGluZV9sb3dfcmVzX3BvbHlnb24uemlw' }
    - { zipname: 'Sub-antarctic_coastline_medium_res_polygon', dbtable: 'add_subant_coastline_i', mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Sub-antarctic_coastline_medium_res_polygon.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2NvYXN0bGluZXMvc2hwL1N1Yi1hbnRhcmN0aWNfY29hc3RsaW5lX21lZGl1bV9yZXNfcG9seWdvbi56aXA%3D' }
    - { zipname: 'Coastline_medium_res_polygon',               dbtable: 'add_ant_coastline_i',    mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Coastline_medium_res_polygon.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2NvYXN0bGluZXMvc2hwL0NvYXN0bGluZV9tZWRpdW1fcmVzX3BvbHlnb24uemlw' }
    - { zipname: 'Sub-antarctic_coastline_high_res_polygon',   dbtable: 'add_subant_coastline_h', mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Sub-antarctic_coastline_high_res_polygon.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2NvYXN0bGluZXMvc2hwL1N1Yi1hbnRhcmN0aWNfY29hc3RsaW5lX2hpZ2hfcmVzX3BvbHlnb24uemlw' }
    - { zipname: 'Coastline_high_res_polygon',                 dbtable: 'add_ant_coastline_h',    mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Coastline_high_res_polygon.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2NvYXN0bGluZXMvc2hwL0NvYXN0bGluZV9oaWdoX3Jlc19wb2x5Z29uLnppcA%3D%3D' }
    - { zipname: 'Facilities_point',                           dbtable: 'add_locations',          mode: 'c', url: 'http://add.antarctica.ac.uk/repository/entry/get/Facilities_point.zip?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2h1bWFuX3ByZXNlbmNlL3NocC9GYWNpbGl0aWVzX3BvaW50LnppcA%3D%3D' }
    
- name: delete tmp directory
  become: yes
  become_user: root
  file: path=/tmp/scar_add state=absent

