---

- name: check for master
  stat:
    path: "{{ trigger_file }}"
  register: im_the_master

- name: set is_master to true if trigger file exists
  set_fact:
    is_master: true
  when: im_the_master.stat.exists

- name: otherwise set to false
  set_fact:
    is_master: false
  when: not im_the_master.stat.exists

- name: check for slave
  stat:
    path: "{{ standby_file }}"
  register: im_the_slave

- name: set is_slave to true if standby file exists
  set_fact:
    is_slave: true
  when: im_the_slave.stat.exists

- name: otherwise set to false
  set_fact:
    is_slave: false
  when: not im_the_slave.stat.exists

- name: fail if neither master or slave
  fail:
    msg: "ERROR: I dont know if I should be master or slave. Either '{{ trigger_file }}' or '{{ standby_file }}' must be present."
  when: is_master==false and is_slave==false

- name: fail if both master or slave
  fail:
    msg: "ERROR: I dont know if I should be master or slave. Both '{{ trigger_file }}' and '{{ standby_file }}' cannot be present, delete one!"
  when: is_master==true and is_slave==true

- name: set postgres version
  set_fact:
    psql_version: 11
  when: version is not defined


