# Name:          update-software.yml
# Purpose:       Update the software packages common to the Istjenesten database system on the master/slave system.
# Author(s):     Nick Hughes
# Created:       2018-vii-25
# Modifications: 2018-vii-?  - 
# Copyright:     (c) Norwegian Meteorological Institute, 2018
# Citing:        https://doi.org/10.5281/zenodo.xxxxxx
#
# License:       This file is part of the BIFROST ice charting system.
#                BIFROST is free software: you can redistribute it and/or modify
#                it under the terms of the GNU General Public License as published by
#                the Free Software Foundation, version 3 of the License.
#                http://www.gnu.org/licenses/gpl-3.0.html
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
---

# Add UbuntuUpdates.org 3rd Party Repository: Postgresql
- name: add PostgreSQL apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
- name: add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ lubuntu_version }}-pgdg main' state=present

# Update the cache and then the software
- name: update apt cache
  apt: update_cache=yes
- name: update apt software
  apt: upgrade=yes state=latest
  