# Name:          create-postgresql-users.yml
# Purpose:       Create required users in postgresql db.
# Author(s):     Alistair Everett
# Created:       2019-05-06
# Modifications: 2018-vii-?  - 
# Copyright:     (c) Norwegian Meteorological Institute, 2018
# Citing:        https://doi.org/10.5281/zenodo.xxxxxx
#
# License:       This file is part of the BIFROST ice charting system.
#                BIFROST is free software: you can redistribute it and/or modify
#                it under the terms of the GNU General Public License as published by
#                the Free Software Foundation, version 3 of the License.
#                http://www.gnu.org/licenses/gpl-3.0.html
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
---

# Create postgres user and set password
- name: set the postgres postgresql user password
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: postgres
    encrypted: true 
    ########### temporary plain text password ########
    password: postgres
    login_user: postgres
    port: 5433
    db: postgres

# Create replication role
- name: add replication postgresql user
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: replication
    encrypted: true
    ########### temporary plain text password ########
    password: postgres
    login_user: postgres
    #login_password: "postgres"
    port: 5433
    role_attr_flags: 'REPLICATION'
    db: postgres

# Add replication slots
# NB: this will break the build if the replication slot already exists
# might consider deleting pre-existing on or allowing it to pass if
# it already exists, if the build fails because of this just delete
# /home/postgres and restart
- name: add replication slots
  vars:
    ansible_ssh_pipelining: true
  expect:
    command: psql -d template_postgis -U postgres -c "SELECT * FROM pg_create_physical_replication_slot('10_168_33_20');"
    responses:
      (?i)Password: "postgres"

