# Name:          istjenesten-database-slave-server.yml
# Purpose:       Ansible playbook to create Istjenesten database server Vagrant box.
# Author(s):     Nick Hughes
# Created:       2018-vii-26
# Modifications: 2018-vii-?  - 
# Copyright:     (c) Norwegian Meteorological Institute, 2018
# Citing:        https://doi.org/10.5281/zenodo.xxxxxx
#
# License:       This file is part of the BIFROST ice charting system.
#                BIFROST is free software: you can redistribute it and/or modify
#                it under the terms of the GNU General Public License as published by
#                the Free Software Foundation, version 3 of the License.
#                http://www.gnu.org/licenses/gpl-3.0.html
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
---
- hosts: localhost 
  remote_user: vagrant
  become: true
  become_method: sudo
  
  tasks:

    - name: load variables
      include_vars: roles/common/vars/vars.yml 

    - name: set facts
      include: roles/common/tasks/set_facts.yml

    # stop the PostgreSQL server
    - name: stop postgresql service
      service:
        name: postgresql
        state: stopped

    - name: clean master
      become: true
      become_user: postgres
      include: roles/common/tasks/clean_postgresql.yml
